//go:generate go run generate/versioninfo.go
// Code generated by go generate; DO NOT EDIT.

package main

const Version = "secure {{ .Version }} ({{ .GOOS }}-{{ .GOARCH }}) {{ .GoVersion }}\n{{ .Homepage }}"
