//go:generate go run generate/versioninfo.go
// Code generated by versioninfo.go; DO NOT EDIT.

package main

const Version = "secure v0.1.0 (windows-amd64) go1.10\nhttps://github.com/yi-jiayu/secure"
